import 'package:get/get.dart';

class MyLocale extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "ar": {
          "1": "جنة أكثر متعة إذا قمت بإنشاء حساب",
          "2": "إنشاء حساب",
          "3": "أو",
          "4": "لديك حساب ؟",
          "5": "سجل الدخول ",
          "6": "أسم المستخدم",
          "7": "كلمة المرور",
          "8": "تسجيل الدخول",
          "9": "نسيت كلمة المرور ؟",
          "10": "سجل الدخول بواسطة Apple",
          "11": "سجل الدخول بواسطة Google",
          "12": "سجل الدخول بواسطة Facebook",
          "13": "الاسم الاول",
          "14": "الاسم الاخير",
          "15": "اعد ادخال كلمة المرور",
          "16": "التسجيل",
          "17": "البريد الالكتروني",
          "18": "بالنقر على إنشاء حساب ، فإنك توافق على",
          "19": "شروط الخدمات وسياسة الخصوصية",
          "20": "الأماكن",
          "21": "ابحث عن أماكن",
          "22": "ترفيه ولعب",
          "23": "تعليم وابداع",
          "24": "رياضة ودفاع عن النفس",
          "25":"حيوانات أليفة",
          "26":"تسوق ومشتريات",
          "27":"أماكن خارجية وحدائق",
          "28":"أطعمة ومشروبات",
          "29":"دور ضيافة",
          "30":"حلاقين",
          "31":"تنسيق حفلات",
          "32":"الفعاليات",
          "33":"ابحث عن فعاليات",
          "34":"المفضلة",
          "35":"لا يوجد لديك مفضلة حتى الان",
          "36":"يمكنك التصفح الان وحفظها في مفضلتك",
           "37":"تصفح الان",
        },
        "en": {
          "1": "JANNAH is more fun if you create an account",
          "2": "Create account",
          "3": "or",
          "4": "you already have account ?",
          "5": "Login",
          "6": "UserName",
          "7": "Password",
          "8": "Login",
          "9": "Forgot Password?",
          "10": "Sign in With Apple",
          "11": "sign in with Google",
          "12": "Sign in With Facebook",
          "13": "First Name",
          "14": "Last Name",
          "15": "Re-enter Password",
          "16": "SingUp",
          "17": "Email",
          "18": "By tapping “ Create Account”, you agree to",
          "19": "Terms of Services & Privacy Policy",
          "20": "Places",
          "21": "Search for places",
          "22": "Entertainment and play",
          "23": "Education and creativity",
          "24": "Sports and self-defense",
          "25":"Pets",
          "26":"Shopping and purchases",
          "27":"Outdoor spaces and gardens",
          "28":"Food and drinks",
          "29":"Guesthouse",
          "30":"Barbers",
          "31":"Party coordination",
          "32":"activities",
          "33":"Search for activities",
          "34":"Favorite",
          "35":"You didn't add any thing to your Favorite yet",
          "36":"you can now",
          "37":"Discover now",


        }
      };
}
